<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.4.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма өтінім қалдыру',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'agtechnoservice@mail.ru',
		'to' => 'agtechnoservice@mail.ru'
	),
	'fields' => array(
		'custom_U11534' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Аты-жөні',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Аты-жөні\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'элктрондық адрес',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'элктрондық адрес\' не может быть пустым.',
				'format' => 'Поле \'элктрондық адрес\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U11539' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Компания',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Компания\' не может быть пустым.'
			)
		),
		'custom_U11516' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Жүмыс мекен жайы',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Жүмыс мекен жайы\' не может быть пустым.'
			)
		),
		'custom_U11530' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Қала',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Қала\' не может быть пустым.'
			)
		),
		'custom_U11520' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Хабарлама',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Хабарлама\' не может быть пустым.'
			)
		),
		'custom_U11525' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Жұмыс номері',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Жұмыс номері\' не может быть пустым.'
			)
		),
		'custom_U11543' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Ұялы номері',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ұялы номері\' не может быть пустым.'
			)
		),
		'custom_U11512' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Үйдің мекен жайы',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Үйдің мекен жайы\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
